### ISSUE TITLE
Could not pass event InventoryCloseEvent to RPGChest v1.0.0

### ISSUE THREAD

**Issue by VacAge** [spigot-gillesm/rpg-chest#16]
[19:01:42 ERROR]: Could not pass event InventoryCloseEvent to RPGChest v1.0.0
java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.InventoryHolder.getInventory()" because the return value of "org.bukkit.inventory.Inventory.getHolder()" is null
        at com.gilles_m.rpg_chest.listener.PlayerListener.onPlayerCloseInventory(PlayerListener.java:84) ~[RPGChest-1.0.0.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:git-Purpur-1832]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:678) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:1554) ~[purpur-1.19.2.jar:git-Purpur-1832]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClose(ServerGamePacketListenerImpl.java:3166) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClose(ServerGamePacketListenerImpl.java:3159) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClosePacket.handle(ServerboundContainerClosePacket.java:15) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClosePacket.a(ServerboundContainerClosePacket.java:10) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.2.jar:git-Purpur-1832]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1368) ~[purpur-1.19.2.jar:git-Purpur-1832]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[purpur-1.19.2.jar:git-Purpur-1832]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1345) ~[purpur-1.19.2.jar:git-Purpur-1832]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1338) ~[purpur-1.19.2.jar:git-Purpur-1832]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1416) ~[purpur-1.19.2.jar:git-Purpur-1832]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1194) ~[purpur-1.19.2.jar:git-Purpur-1832]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1832]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by VacAge** [comment]
https://www.klgrth.io/paste/sq8zd
https://www.klgrth.io/paste/64z79

**Comment by VacAge** [comment]
I use a PIN to log in to the server from the developer PINPromt Author: HexedHero

**Comment by spigot-gillesm** [comment]
Hello, thanks for the bug review. I published [here](https://github.com/spigot-gillesm/rpg-chest/releases/tag/Pre-release) a pre-release build that should prevent the NPE from happening. Please download and try the version 1.0.1 to check that the fix is working.
Thank you!

**Comment by VacAge** [comment]
Everything is stable, there are no errors.
